### PR TITLE
[docs] add new changes specification format

### PR DESCRIPTION
**Pull request by ivanalejandro0**
Instead of adding a file for each change we encourage to add lines in
this new file.

### CODE REVIEW

**Comment by ivanalejandro0** [comment]
What should we add on the `Misc` section?
packaging, documentation, scripts, any other idea?
The reason behind this new section is to show on each release that there is a lot of work being done and not really seen in a feature/bugfix list.

**Comment by kalikaneko** [comment]
@ivanalejandro0 all that sounds good. I'd add CI maybe

**Comment by ivanalejandro0** [comment]
> @ivanalejandro0 all that sounds good. I'd add CI maybe

A CI category or suggest CI to things to add into Misc?

**Comment by ivanalejandro0** [comment]
When we get this merged we should apply to the other repositories as well so we get the cool readme+changes on pypi for all the leap libs.

**Comment by kalikaneko** [comment]
> A CI category or suggest CI to things to add into Misc?

I think I prefer the latest.
We should also include examples of issues reported in Gihub issues only, what do you think?

**Comment by kalikaneko** [comment]
Also, I think a Known Issues section might be great.

**Comment by kalikaneko** [comment]
I have copied this into #932, we can close this.

**Pull request closed without merging**
