### PR TITLE
[feat] use docker to test .deb packages

### PR DESCRIPTION
**Pull request by ivanalejandro0**
Add scripts to easily test (stable or unstable) debian packages.

- Resolves: #6715

### CODE REVIEW

**Comment by ivanalejandro0** [comment]
I'm not really sure about including the experimental repo key, thoughts?

**Comment by kalikaneko** [comment]
I think it's ok

**Comment by kalikaneko** [comment]
rebased && merged.
great to have this in the testing battery! :D

**Comment by varac** [comment]
@ivanalejandro0 could you please update the README.rst how to run the test with docker ?

**Comment by ivanalejandro0** [comment]
> @ivanalejandro0 could you please update the README.rst how to run the test with docker ?

@varac sure, sorry for the scarce docs. I've used this scripts to test the latest .deb packages. I'll add some docs for this soon.

**Pull request closed without merging**
