### PR TITLE
[bug] enable atexit subprocess termination

### PR DESCRIPTION
**Pull request by ivanalejandro0**
- Resolves: #6426
- Resolves: #6681

### CODE REVIEW

**Comment by kalikaneko** [comment]
from my tests, re-enabling the atexit hook it seems to be working fine.
do you have any idea about why it was disabled previously?

**Comment by ivanalejandro0** [comment]
> from my tests, re-enabling the atexit hook it seems to be working fine.
> do you have any idea about why it was disabled previously?

cool!
No idea :/ ... I'm going to search history to see if I can figure it out.

**Comment by ivanalejandro0** [comment]
This seems to be the commit that disables it: https://github.com/leapcode/bitmask_client/commit/543296a62235d5303662720d3f341e1dc10d478e
Since the handlers changed a while ago I think that the problem of the handlers calling `quit` does not exist anymore.

**Comment by kalikaneko** [comment]
nice. So, I think we could cleanup this and merge :)

**Comment by ivanalejandro0** [comment]
> nice. So, I think we could cleanup this and merge :)

done

**Pull request merged**
