### PR TITLE
Refactor SRPAuth and SRPRegister

### PR DESCRIPTION
**Pull request by dudadornelles**

### CODE REVIEW

**Comment by kalikaneko** [comment]
@ivanalejandro0 can this be included in 0.9.0 release?

**Comment by ivanalejandro0** [comment]
Hey there! the pull request looks good, sorry it took me so long to make time for it.
I've rebased this branch to use our current commit style (see https://github.com/leapcode/bitmask_client/blob/develop/docs/leap-commit-template.README) and branch names and pushed to my fork so you can see - https://github.com/ivanalejandro0/bitmask_client/tree/feature/refactor-srp
Please update this pull request with those changes.

Also check the tests, there are two of them failing, I think that is due the srp implementation changes.

**Comment by kalikaneko** [comment]
@ivanalejandro0 after it being so long on our side, I wonder if it's better if we merge this commit in a branch, and then apply another commit on top with whatever changes needed.

**Comment by ivanalejandro0** [comment]
@kalikaneko you're right, I'm closing this and I'll merge the rebased commits.

**Pull request closed without merging**
